/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookLogsRouteImport } from './routes/webhook-logs'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardNicheRouteImport } from './routes/dashboard.niche'
import { Route as DashboardNicheHospitalRouteImport } from './routes/dashboard.niche.hospital'
import { Route as DashboardNicheFoodRouteImport } from './routes/dashboard.niche.food'
import { Route as ApiPublicTwilioWebhookRouteImport } from './routes/api.public.twilio-webhook'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api.public.paystack-webhook'
import { Route as DashboardNicheFoodOrdersRouteImport } from './routes/dashboard.niche.food.orders'
import { Route as DashboardNicheFoodMenuRouteImport } from './routes/dashboard.niche.food.menu'

const WebhookLogsRoute = WebhookLogsRouteImport.update({
  id: '/webhook-logs',
  path: '/webhook-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNicheRoute = DashboardNicheRouteImport.update({
  id: '/niche',
  path: '/niche',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNicheHospitalRoute = DashboardNicheHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => DashboardNicheRoute,
} as any)
const DashboardNicheFoodRoute = DashboardNicheFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => DashboardNicheRoute,
} as any)
const ApiPublicTwilioWebhookRoute = ApiPublicTwilioWebhookRouteImport.update({
  id: '/api/public/twilio-webhook',
  path: '/api/public/twilio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardNicheFoodOrdersRoute =
  DashboardNicheFoodOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => DashboardNicheFoodRoute,
  } as any)
const DashboardNicheFoodMenuRoute = DashboardNicheFoodMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardNicheFoodRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/dashboard/niche': typeof DashboardNicheRouteWithChildren
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/dashboard/niche': typeof DashboardNicheRouteWithChildren
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/webhook-logs': typeof WebhookLogsRoute
  '/dashboard/niche': typeof DashboardNicheRouteWithChildren
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/webhook-logs'
    | '/dashboard/niche'
    | '/api/public/paystack-webhook'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/webhook-logs'
    | '/dashboard/niche'
    | '/api/public/paystack-webhook'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/webhook-logs'
    | '/dashboard/niche'
    | '/api/public/paystack-webhook'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  WebhookLogsRoute: typeof WebhookLogsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicTwilioWebhookRoute: typeof ApiPublicTwilioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook-logs': {
      id: '/webhook-logs'
      path: '/webhook-logs'
      fullPath: '/webhook-logs'
      preLoaderRoute: typeof WebhookLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/niche': {
      id: '/dashboard/niche'
      path: '/niche'
      fullPath: '/dashboard/niche'
      preLoaderRoute: typeof DashboardNicheRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/niche/hospital': {
      id: '/dashboard/niche/hospital'
      path: '/hospital'
      fullPath: '/dashboard/niche/hospital'
      preLoaderRoute: typeof DashboardNicheHospitalRouteImport
      parentRoute: typeof DashboardNicheRoute
    }
    '/dashboard/niche/food': {
      id: '/dashboard/niche/food'
      path: '/food'
      fullPath: '/dashboard/niche/food'
      preLoaderRoute: typeof DashboardNicheFoodRouteImport
      parentRoute: typeof DashboardNicheRoute
    }
    '/api/public/twilio-webhook': {
      id: '/api/public/twilio-webhook'
      path: '/api/public/twilio-webhook'
      fullPath: '/api/public/twilio-webhook'
      preLoaderRoute: typeof ApiPublicTwilioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/niche/food/orders': {
      id: '/dashboard/niche/food/orders'
      path: '/orders'
      fullPath: '/dashboard/niche/food/orders'
      preLoaderRoute: typeof DashboardNicheFoodOrdersRouteImport
      parentRoute: typeof DashboardNicheFoodRoute
    }
    '/dashboard/niche/food/menu': {
      id: '/dashboard/niche/food/menu'
      path: '/menu'
      fullPath: '/dashboard/niche/food/menu'
      preLoaderRoute: typeof DashboardNicheFoodMenuRouteImport
      parentRoute: typeof DashboardNicheFoodRoute
    }
  }
}

interface DashboardNicheFoodRouteChildren {
  DashboardNicheFoodMenuRoute: typeof DashboardNicheFoodMenuRoute
  DashboardNicheFoodOrdersRoute: typeof DashboardNicheFoodOrdersRoute
}

const DashboardNicheFoodRouteChildren: DashboardNicheFoodRouteChildren = {
  DashboardNicheFoodMenuRoute: DashboardNicheFoodMenuRoute,
  DashboardNicheFoodOrdersRoute: DashboardNicheFoodOrdersRoute,
}

const DashboardNicheFoodRouteWithChildren =
  DashboardNicheFoodRoute._addFileChildren(DashboardNicheFoodRouteChildren)

interface DashboardNicheRouteChildren {
  DashboardNicheFoodRoute: typeof DashboardNicheFoodRouteWithChildren
  DashboardNicheHospitalRoute: typeof DashboardNicheHospitalRoute
}

const DashboardNicheRouteChildren: DashboardNicheRouteChildren = {
  DashboardNicheFoodRoute: DashboardNicheFoodRouteWithChildren,
  DashboardNicheHospitalRoute: DashboardNicheHospitalRoute,
}

const DashboardNicheRouteWithChildren = DashboardNicheRoute._addFileChildren(
  DashboardNicheRouteChildren,
)

interface DashboardRouteChildren {
  DashboardNicheRoute: typeof DashboardNicheRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNicheRoute: DashboardNicheRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  WebhookLogsRoute: WebhookLogsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicTwilioWebhookRoute: ApiPublicTwilioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
